### ISSUE TITLE
Any interest porting this over for x86 support?

### ISSUE THREAD

**Issue by jmctune** [qb-0/PyMeow#11]
Hey there,

Really cool library. I'm excited to see something actively being developed around memory and process manipulation. I've been using `pymem` for awhile, but development on that project seems stale. 

Are there any plans on supporting x86 processes by chance? I'd love to use this on one of my projects.

Thanks for sharing!

**Comment by qb-0** [comment]
Hey,

thank you. PyMeow does support 32bit processes (e.g.: https://github.com/qb-0/PyMeow/blob/master/examples/ac_esp.py). The binary releases are just compiled in x64 so they're just importable from a x64 python binary as well.

**Comment by jmctune** [comment]
Hm, sure does! I think I misspoke on what I was actually trying to solve here.

It does work with 64-bit Python, but not 32. The game I work on is strictly 32-bit and the interpreter I inject also needs to be the same. My less confusing question would be:

Is there any interest in supporting 32-bit Python?

Thanks again, qb.

**Comment by qb-0** [comment]
I see. Theoretically you're able to compile a 32bit build with the compiler switch `i386` on the [config](https://github.com/qb-0/PyMeow/blob/master/pymeow.nim.cfg#L5).

My first tries are failing caused by type conversions. I probably messed some stuff up there. But I'm also cross compiling for windows on linux as I currently don't got a windows machine here. Needs some more investigation.

**Comment by lxy2001910** [comment]
那位大佬能出个详细安装的教材感谢
